name: Angular Testing CI

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    test-and-lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  
            - name: Install pakcages 
              working-directory: ./Web/ClientApp
              run: npm ci
              
            - name: Testing app
              working-directory: ./Web/ClientApp
              run: npm run test:prod
              
            - name: Linting app 
              working-directory: ./Web/ClientApp
              run: npm run lint
